DROP TABLE IF EXISTS menus;

CREATE TABLE menus(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Name TEXT,
	price INTEGER,
    image TEXT,
    description TEXT
);
